[G4-Process] API implementation
2021-ZJU-Software-engineering/software-engineering-backend pull request #27
Opened 2021-05-23 07:49 UTC by PAN-Ziyue

## What we have done

- [x] coarse implementation of the handlers

## TODO

- [ ] authentication for restricted handlers
- [ ] filter the unwanted attributes in returned models
- [ ] test on these handlers
- [ ] some initial data

2021-05-25 06:57 UTC, AsterNighT commented
Is is done now? If it is not ready yet, you can add a [WIP] in the title

2021-05-30 15:33 UTC, AsterNighT requested changes
Pls don't merge master. Use rebase instread. Your file changes are a mess now.

2021-05-30 15:33 UTC, AsterNighT commented on .github/workflows/ci.yml
> +        run: |
don't put it here. Update go.mod and go.sum instead

2021-05-30 15:33 UTC, AsterNighT commented on .github/workflows/ci.yml
> +          go get github.com/labstack/gommon/log
ditto

2021-05-30 15:33 UTC, AsterNighT commented on .github/workflows/ci.yml
> +          go get github.com/labstack/gommon/log
ditto

2021-05-30 15:36 UTC, RupertPaoZ reviewed
please use rebase

2021-05-30 15:38 UTC, AsterNighT commented
If your are not sure how to make up this mess, you could create a new branch and cherrypick your changes, that'll be easier.

2021-05-30 15:52 UTC, PAN-Ziyue commented
> please use rebase

> If your are not sure how to make up this mess, you could create a new branch and cherrypick your changes, that'll be easier.


Clear the messy changes.

2021-05-30 16:00 UTC, AsterNighT requested changes

2021-05-30 16:00 UTC, AsterNighT commented on pkg/process/handler.go
> +		log.Error("UpdateMileStoneByDoctor failed due to", err)
umm, why not use `c.Logger` as it is done elsewhere?

2021-05-30 16:00 UTC, AsterNighT commented on pkg/process/handler.go
> +
And pls fmt your file

2021-05-30 16:58 UTC, AsterNighT requested changes

2021-05-30 16:58 UTC, AsterNighT commented on pkg/process/handler.go
> +	RegistrationID, err := strconv.ParseUint(c.QueryParam("RegistrationID"), 10, 64)
why is this `RegistrationID` UpperCamalCase?

2021-05-30 16:58 UTC, AsterNighT commented on pkg/process/handler.go
> +	var Milestone MileStone
ditto

2021-05-30 16:58 UTC, AsterNighT commented on pkg/process/handler.go
> +	var Checked bool
ditto

2021-05-30 16:58 UTC, AsterNighT commented on pkg/process/handler.go
> +	var Checked bool
And else

2021-05-30 17:08 UTC, PAN-Ziyue commented
sovled code style

2021-05-31 00:36 UTC, AsterNighT requested changes

2021-05-31 00:36 UTC, AsterNighT commented on pkg/process/handler.go
>  	var Registration Registration
```suggestion
	var registration Registration
```

2021-05-31 00:40 UTC, PAN-Ziyue commented on pkg/process/handler.go
>  	var Registration Registration
It is fixed

2021-05-31 00:58 UTC, AsterNighT approved these changes

2021-05-31 01:00 UTC, AsterNighT commented
WAM, so what's the usage of `RegistrationStatusEnum` in `pkg/process/model.go`? Is it useles??

2021-05-31 01:07 UTC, PAN-Ziyue commented
> WAM, so what's the usage of `RegistrationStatusEnum` in `pkg/process/model.go`? Is it useless?

We have to control the status to limited states. Maybe used in `validator`.

2021-05-31 01:12 UTC, AsterNighT commented
ok

2021-05-31 01:12 UTC, merged