modify doctor and patient
2021-ZJU-Software-engineering/software-engineering-backend pull request #64
Opened 2021-06-28 12:32 UTC by FUTURETECH6

2021-06-29 04:43 UTC, AsterNighT requested changes

2021-06-29 04:43 UTC, AsterNighT commented on pkg/account/handler.go
> +// @Router /account/create [POST]
```suggestion
// @Router /account/setdoctor [POST]
```

besides, set doctor is an awful name. What does it set?

2021-06-29 04:43 UTC, AsterNighT commented on pkg/account/handler.go
> +// @Router /account/create [POST]
```suggestion
// @Router /account/setpatient [POST]
```

awful name too

2021-07-01 12:18 UTC, AsterNighT approved these changes

2021-07-01 12:19 UTC, AsterNighT requested changes
Uhh, it cannot build

2021-07-02 16:18 UTC, RupertPaoZ reviewed
we need a birthday attr in patient or account

2021-07-02 16:19 UTC, RupertPaoZ commented
and sex

2021-07-02 16:36 UTC, RupertPaoZ commented
and gender

2021-07-03 05:43 UTC, AsterNighT approved these changes

2021-07-03 05:43 UTC, merged